name: Test juvix-arm-specs
'on':
  push:
    branches:
      - main
  pull_request: null
  workflow_dispatch: null
jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: Download the Juvix binary
        uses: jaxxstorm/action-install-gh-release@v1.10.0
        with:
          repo: anoma/juvix
          cache: enable
      - name: Clean & Update Dependencies
        run: juvix clean --global && juvix clean && juvix dependencies update
      - name: Type Check
        run: juvix typecheck
      - name: Format Check
        run: juvix format
